// Generated by BUCKLESCRIPT VERSION 1.0.3 , PLEASE EDIT WITH CARE
'use strict';

var Jquery = require("jquery");

function jquery(prim) {
  return Jquery(prim);
}

function css(prim, prim$1, prim$2) {
  return prim$2.css(prim, prim$1);
}

function outerHeight(prim, prim$1) {
  return prim$1.outerHeight(prim);
}

exports.jquery      = jquery;
exports.css         = css;
exports.outerHeight = outerHeight;
/* jquery Not a pure module */
