// Generated by BUCKLESCRIPT VERSION 1.0.3 , PLEASE EDIT WITH CARE
'use strict';


function readFilter(s) {
  switch (s) {
    case "active" : 
        return /* Active */1;
    case "all" : 
        return /* All */0;
    case "completed" : 
        return /* Completed */2;
    default:
      return /* All */0;
  }
}

exports.readFilter = readFilter;
/* No side effect */
